### ISSUE TITLE
epoll install on pine64

### ISSUE THREAD

**Issue by dkebler** [fivdi/onoff#153]
During install on a pine64 (allwinner cpu) running bionic (armbian) with mainline kernel 4.19 I get the following.   So when it says no module `compiler.ast` is that a kernel module I might be missing?

```
Traceback (most recent call last):
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 13, in <module>
    import gyp
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 8, in <module>
    import gyp.input
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 5, in <module>
    from compiler.ast import Const
ImportError: No module named compiler.ast
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.38-sunxi64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/uci-gpio/node_modules/epoll
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
```

At this time I am not using interrupts so can I just ignore this or will the rest of on/off fail if epoll C code was not built?

**Comment by dkebler** [comment]
After some more digging this looks like a python install problem  
I guess node-gyp needs python...ironically,
That armbian distro had python3 already loaded.  Any suggestions on how to get the missing python module(s) loaded?

**Comment by dkebler** [comment]
`sudo apt install python-dev`  will load missing module dependencies.

https://techoverflow.net/2018/06/04/fixing-node-npm-importerror-no-module-named-compiler-ast-on-ubuntu-18-04/
