### ISSUE TITLE
Cannot run on non Rpi system

### ISSUE THREAD

**Issue by jakew009** [fivdi/onoff#186]
Our project sometimes runs on an Rpi based system, sometimes on a non Rpi based system. We don't use the GPIO features on the non Rpi systems but the code is still there.

On node 12.14.0 when i try and run the simplest test 

```
const Gpio = require('onoff').Gpio
console.log(Gpio.accessible)
```

I get the following error. What on earth am I doing wrong? I have tried everything to rebuild / recompile.

```
/home/jake/webdev/gpio-play/node_modules/bindings/bindings.js:121
        throw e;
        ^
Error: The module '/home/jake/webdev/gpio-play/node_modules/epoll/build/Release/epoll.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at bindings (/home/jake/webdev/gpio-play/node_modules/bindings/bindings.js:112:48)
    at module.exports._ (/home/jake/webdev/gpio-play/node_modules/epoll/epoll.js:7:31)
    at Object.<anonymous> (/home/jake/webdev/gpio-play/node_modules/epoll/epoll.js:15:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

**Comment by jakew009** [comment]
Ignore me I am an idiot, was using nvm and had a different node version as sudo / non sudo :(
