### ISSUE TITLE
Unexporting GPIOs no longer allowed on the BBB with Debian 8.4 2016-05-13

### ISSUE THREAD

**Issue by fivdi** [fivdi/onoff#50]
Attempting to unexport a GPIO on the BeagleBone Black when using the Debian 8.4 2016-05-13 image results in errors. Here's an example:
```
fs.js:613
    return binding.writeBuffer(fd, buffer, offset, length, position);
                   ^
Error: EINVAL, invalid argument
    at Error (native)
    at Object.fs.writeSync (fs.js:613:20)
    at Object.fs.writeFileSync (fs.js:1108:21)
    at Gpio.unexport (/root/lcd/node_modules/onoff/onoff.js:302:6)
    at Lcd.close (/root/lcd/node_modules/lcd/lcd.js:219:11)
    at process.<anonymous> (/root/lcd/node_modules/lcd/example/digital-clock-8x1.js:19:7)
    at process.emit (events.js:104:17)
    at Signal.wrap.onsignal (node.js:655:46)
```

**Comment by fivdi** [comment]
This issue occurs when cape_universal is enabled. cape_universal results in many gpios being automatically exported to userspace and it's no longer possible to unexport them by writing their number to `/sys/class/gpio/unexport`.

Fixed in onoff@1.1.1 with e8c3be8ced9290e8da309408dcd8555abba4babf. onoff@1.1.1 now functions correctly irrespective of whether cape_universal is enabled or not.
