### ISSUE TITLE
EACCES: permission denied errors

### ISSUE THREAD

**Issue by fivdi** [fivdi/onoff#75]
Sometines there are `EACCES: permission denied` errors when running [performance-async.js](https://github.com/fivdi/onoff/blob/v1.1.4/test/performance-async.js) with onoff v1.1.4, Node.js v4.8.4 and Raspbian-2017-07-05 on a Raspberry Pi 1 B.
```
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/sys/class/gpio/gpio17/value'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at new Gpio (/home/pi/onoff/v4/node_modules/onoff/onoff.js:146:21)
    at /home/pi/onoff/v4/node_modules/onoff/test/performance-async.js:5:11
    at Object.<anonymous> (/home/pi/onoff/v4/node_modules/onoff/test/performance-async.js:33:2)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

**Comment by fivdi** [comment]
Fixed in 7beb74b85485636b3772619e5d4bd0fd8dc12ae2 and published with onoff v1.1.5.
