### ISSUE TITLE
Missing epoll binding files in electron project using webpack

### ISSUE THREAD

**Issue by MattiaCostamagna** [fivdi/onoff#83]
Hi,

I'm using `onoff` in a library that I need to import in an electron project. This project uses webpack to pack the source code, and it compiles nicely, but when I try to launch it I get the following error 

A JavaScript error occurred in the main process
Uncaught Exception:
Error: Could not locate the bindings file. Tried:
 → /path/to/my/project/dist/build/epoll.node
 → /path/to/my/project/dist/build/Debug/epoll.node
 → /path/to/my/project/dist/build/Release/epoll.node
 → /path/to/my/project/dist/out/Debug/epoll.node
 → /path/to/my/project/dist/Debug/epoll.node
 → /path/to/my/project/dist/out/Release/epoll.node
 → /path/to/my/project/dist/Release/epoll.node
 → /path/to/my/project/dist/build/default/epoll.node
 → /path/to/my/project/dist/compiled/7.9.0/linux/arm/epoll.node
    at bindings (/path/to/my/project/dist/main.js:805:9)
    at Object.<anonymous> (/path/to/my/project/dist/main.js:705:41)
    at __webpack_require__ (/path/to/my/project/dist/main.js:20:30)
    at Object.<anonymous> (/path/to/my/project/dist/main.js:340:11)
    at __webpack_require__ (/path/to/my/project/dist/main.js:20:30)
    at Object.<anonymous> (/path/to/my/project/dist/main.js:196:14)
    at __webpack_require__ (/path/to/my/project/dist/main.js:20:30)
    at Object.<anonymous> (/path/to/my/project/dist/main.js:103:15)
    at __webpack_require__ (/path/to/my/project/dist/main.js:20:30)
    at /path/to/my/project/dist/main.js:63:18

I'm using a RaspberryPi and I've already tried to recompile the epoll module in my node_modules, but without success.
My electron version is 1.7.9.

Do you know what shall I do?
Thank you in advance!

**Comment by MattiaCostamagna** [comment]
I've just found out that the epoll dependency uses node-bindings to import its stuff. Node bindings does not work with webpack since it's like a dynamic require, so webpack does non know what to import when creating the bundle file. I installed `node-loader` that allows you to import a `.node` file and replaced `module.exports = require('bindings')('epoll.node');` with `module.exports = require('./build/Release/epoll.node');` in node_modules/epoll/epoll.js, and now its working fine.

Since I don't like it much as a solution because I have to edit a file in the node_modules directory, I'll look for a way to make webpack do that. 

I know it is not strictly related to onoff module, but I think it'd be nice to leave the issue here for other peolple who may have the same problem in the future.

**Comment by MattiaCostamagna** [comment]
Ok, so this is what I've done to make it work:

1.  Install the dependency 'string-replace-webpack-plugin' with `npm i -D string-replace-webpack-plugin`
2.  Install the webpack loader node-loader with `npm i -D node-loader`
3.  Add the following rule to the webpack config:
    ```javascript
    {
        test: /epoll\.js$/,
        loader: StringReplacePlugin.replace({
            replacements: [
                {
                    pattern: /require\(\'bindings\'\)\(\'epoll\.node\'\)\;/ig,
                    replacement: function () {
                        return "require('./build/Release/epoll.node');";
                    }
                }
            ]
        })
    }
    ```
4.  Add the following rule to the webpack config:
    ```
    {
        test: /\.node$/,
        use: 'node-loader'
    }
    ```
5.  In the plugin array of the configuration object, add the item `new StringReplacePlugin()`

This will replace the string `require('bindings')('epoll.node');` with `require('./build/Release/epoll.node');` that will be correctly parsed by node-loader.
This solution is working for me if I launch the project with `electron main.js` and if I compile it and generate the deb file to install.

If you've got a better solution, please let me know!
I'll close this issue for now.
